config/routes.rb
Rails.application.routes.draw do


  resources :recipes
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end


  resources :beers do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  resources :tweets

  resources :movies do
    member do
      post 'watched', to: 'watches#create'
      delete 'unwatched', to: 'watches#destroy'
    end
  end

  resources :comments do
    member do
      post 'comments', to: 'comments#create', as: "create"
      delete 'uncomment', to: 'comments#destroy', as: "delete"
    end
  end



  resources :nominations


  get 'pages/home'

  root "pages#home"

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord

  validates :name, :abv, :style, presence: true

  acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :nominatings
  has_many :nominations, through: :nominatings

  def nomination_list
    self.nominations.collect do |nomination|
      nomination.name
    end.join(", ")
  end

  def nomination_list=(nominations_string)
    nomination_names = nominations_string.split(",").collect{ |s| s.strip}.uniq
    new_or_found_nominations = nomination_names.collect { |name| Nomination.find_or_create_by(name: name) }
    self.nominations = new_or_found_nominations
  end

  acts_as_votable
  acts_as_commentable
end

app/models/nominating.rb
class Nominating < ApplicationRecord
  belongs_to :nomination
  belongs_to :movie
end

app/models/nomination.rb
class Nomination < ApplicationRecord
  has_many :nominatings
  has_many :movies, through: :nominatings

end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: {maximum: 140 }

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets

   validates :username, presence: true, uniqueness: true, length: {minimum: 6}
   validates :name, presence: true

   acts_as_followable
   acts_as_follower
   acts_as_voter
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def show
    @tweets = Tweet.where(user: current_user.all_following)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MoviesHelper

  def index
    @movies = Movie.all.order("title DESC").sort_by { |x,y| x.nominations.length }.reverse
    @users = User.all.order("name DESC").sort_by { |x,y| (x.get_up_voted Movie).length }.reverse
  end

  def show
    @movie = Movie.find_by(id: params[:id])
    @nominations = @movie.nominations.order('name ASC')
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save

    redirect_to movies_path
  end

  def nomination_list
    nominations.join(", ")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def movie_params
    params.require(:movie).permit(:title, :nomination_list)
  end

end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/movies/index.html.erb
  <% if !user_signed_in? %>
    <div class="jumbotron bg-dark text-center">
      <h2>Sign in to keep track.</h2>
      <br>
      <%= link_to "Sign in", signin_path, class:"btn btn btn-secondary"  %>
      <%= link_to "Sign up", signup_path, class:"btn btn btn-light"  %>
    </div>
  <% end %>
  <div class="row d-flex justify-content-between">
    <div class="col-7 list-group text-center">
      <div class="row list-group-item">
        <div class="col-12">
          <h4>Oscars</h4>
        </div>
      </div>
      <div class="row list-group-item d-flex justify-content-around align-items-center">
        <div class="col-4">
          <h5>Title</h5>
        </div>
        <div class="col-4">
          <h5>
            <%= link_to nominations_path, class:"nominations_link" do %>
              Nominations
            <% end %>
          </h5>
        </div>
        <% if user_signed_in? %>
        <div class="col-4">
          <h5>Watched

              (<%= (current_user.get_up_voted Movie).length %>)

          </h5>
        </div>
        <% end %>
      </div>
      <% @movies.each do |movie| %>
        <div class="row list-group-item d-flex justify-content-around align-items-center">
          <div class="col-4">
            <%= link_to movie.title, movie_path(movie) %>
          </div>
          <div class="col-4">
            <%= movie.nominations.length %>
          </div>
          <% if user_signed_in? %>
            <div class="col-4">
              <% if !current_user.voted_up_on? movie %>
                <%= link_to watched_movie_path(movie), method: :post, id: movie.title do %>
                  <h5><i class= 'btn fa fa-eye-slash unvote'></i></h5>
                <% end %>
              <% else %>
                <%= link_to unwatched_movie_path(movie), method: :delete, id: movie.title do %>
                  <h4><i class= 'btn fa fa-eye vote'></i></h4>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="col-4 list-group text-center">
      <div class="row list-group-item">
        <div class="col-12">
          <h4>Leaderboard</h4>
        </div>
      </div>
      <div class="row list-group-item d-flex justify-content-around align-items-center ">
        <div class="col-6">
          <h5>Name</h5>
        </div>
        <div class="col-6">
          <h5>Watch Count</h5>
        </div>
      </div>
      <% @users.each do |user| %>
        <%= link_to user_path(user.username), class:"row list-group-item list-group-item-action d-flex justify-content-around align-items-center" do %>
          <div class="col-6">
            <%= user.name %>
          </div>
          <div class="col-6">
            <%= (user.get_up_voted Movie).length %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/movies/show.html.erb
<div class="card bg-dark">
  <div class="card-header">
    <h1><%= @movie.title %></h1>
  </div>

  <div class="card-body">
    <h5 class="card-title">Nominations:</h5>
    <% @nominations.each do |nomination| %>
      <%= link_to nomination_path(nomination) do %>
        <span class="badge badge-light name-badge">
          <%= nomination.name %>
        </span>
      <% end %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="card-body">
      <%= form_tag create_comment_path, method: :post do %>
        <%= hidden_field_tag "id", @movie.id %>
        <%= label_tag 'comment:' %>
        <%= text_area_tag :comment, nil, class: 'form-control' %>
        <br>
        <%= submit_tag "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
  <div class="card-body">
    <h6>Comments:</h6>
    <ul class="list-group list-group-flush">
      <% @movie.comments.all.each do |comment| %>
        <li class="list-group-item">
          <%= link_to user_path(comment.user.username) do %>
            <%= comment.user.username %>
          <% end %>
          <br>
          <%= comment.comment %>
          <% if comment.user == current_user %>
            <%= link_to delete_comment_path(@movie,comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn float-right" do %>
              <i class="fa fa-trash"></i>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="card-footer">
    <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-dark" disabled>Back to:</button>
      <button type="button" class="btn btn-dark" data-toggle="tooltip" data-placement="bottom" title="Nominations">
        <%= link_to nominations_path do %>
            <i class="fa fa-trophy"></i>
        <% end %>
      </button>
      <button type="button" class="btn btn-dark" data-toggle="tooltip" data-placement="bottom" title="Movies">

      <%= link_to movies_path do %>
          <i class="fa fa-film"></i>
      <% end %>
    </button>

    </div>
  </div>



</div>