config/routes.rb
Rails.application.routes.draw do


  resources :recipes
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end


  resources :beers do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  resources :tweets

  resources :movies do
    member do
      post 'watched', to: 'watches#create'
      delete 'unwatched', to: 'watches#destroy'
    end
  end

  resources :comments do
    member do
      post 'comments', to: 'comments#create', as: "create"
      delete 'uncomment', to: 'comments#destroy', as: "delete"
    end
  end



  resources :nominations


  get 'pages/home'

  root "pages#home"

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord

  validates :name, :abv, :style, presence: true

  acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :nominatings
  has_many :nominations, through: :nominatings

  def nomination_list
    self.nominations.collect do |nomination|
      nomination.name
    end.join(", ")
  end

  def nomination_list=(nominations_string)
    nomination_names = nominations_string.split(",").collect{ |s| s.strip}.uniq
    new_or_found_nominations = nomination_names.collect { |name| Nomination.find_or_create_by(name: name) }
    self.nominations = new_or_found_nominations
  end

  acts_as_votable
  acts_as_commentable
end

app/models/nominating.rb
class Nominating < ApplicationRecord
  belongs_to :nomination
  belongs_to :movie
end

app/models/nomination.rb
class Nomination < ApplicationRecord
  has_many :nominatings
  has_many :movies, through: :nominatings

end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: {maximum: 140 }

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets

   validates :username, presence: true, uniqueness: true, length: {minimum: 6}
   validates :name, presence: true

   acts_as_followable
   acts_as_follower
   acts_as_voter
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  def create
    @beer = Beer.new(beer_params)


      if @beer.save
        redirect_to @beer, notice: 'Beer was successfully created.'
      else
        render :new
    end
  end

  # PATCH/PUT /beers/1
  def update

      if @beer.update(beer_params)
        redirect_to @beer, notice: 'Beer was successfully updated.'
      else
        ender :edit
    end
  end

  # DELETE /beers/1
  def destroy
    @beer.destroy
    redirect_to beers_url, notice: 'Beer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :abv, :style, :price)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def show
    @tweets = Tweet.where(user: current_user.all_following)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets
    @movies = (@user.get_up_voted Movie).order('title ASC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def movie_params
    params.require(:movie).permit(:title, :nomination_list)
  end

end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/users/show.html.erb
<div class="row">
  <div class="col-4">
    <div class="card bg-dark">
      <div class="card-body">
        <h5 class="card-title"><%= @user.username %></h5>
        <p class="card-text"><%= @user.name %></p>
      </div>
      <% if user_signed_in? %>
        <% if current_user.following?(@user) %>
          <%= link_to "Unfollow", unfollow_user_path(@user.username), method: :delete, class:"card-footer btn" %>
        <% else %>
          <%= link_to "Follow", follow_user_path(@user.username), method: :post, class:"card-footer btn" %>
        <% end %>
      <% end %>
    </div>

    <div id="oscarWatch" class="card bg-dark">
      <div class="card-header">
        <h5 class="card-title">
          Oscar Watch
          <span class="float-right">
            <%= link_to nominations_path do %>
              <i class="fa fa-trophy" data-toggle="tooltip" data-placement="bottom" title="Nominations"></i>
            <% end %>

            <%= link_to movies_path do %>
              <i class="fa fa-film" data-toggle="tooltip" data-placement="bottom" title="Movies"></i>
            <% end %>
          </span>
        </h5>

      </div>
      <div class="list-group-flush">
        <% @movies.each do |movie| %>
          <%= link_to movie_path(movie), class: "list-group-item list-group-item-action" do %>
            <%= movie.title %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="col-8">

    <div class="list-group">
      <% @tweets.each do |tweet| %>
        <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= tweet.user.username %></h5>
          </div>
          <p class="mb-1"><%= tweet.content %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>