config/routes.rb
Rails.application.routes.draw do


  resources :recipes
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end


  resources :beers do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  resources :tweets

  resources :movies do
    member do
      post 'watched', to: 'watches#create'
      delete 'unwatched', to: 'watches#destroy'
    end
  end

  resources :comments do
    member do
      post 'comments', to: 'comments#create', as: "create"
      delete 'uncomment', to: 'comments#destroy', as: "delete"
    end
  end



  resources :nominations


  get 'pages/home'

  root "pages#home"

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord

  validates :name, :abv, :style, presence: true

  acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :nominatings
  has_many :nominations, through: :nominatings

  def nomination_list
    self.nominations.collect do |nomination|
      nomination.name
    end.join(", ")
  end

  def nomination_list=(nominations_string)
    nomination_names = nominations_string.split(",").collect{ |s| s.strip}.uniq
    new_or_found_nominations = nomination_names.collect { |name| Nomination.find_or_create_by(name: name) }
    self.nominations = new_or_found_nominations
  end

  acts_as_votable
  acts_as_commentable
end

app/models/nominating.rb
class Nominating < ApplicationRecord
  belongs_to :nomination
  belongs_to :movie
end

app/models/nomination.rb
class Nomination < ApplicationRecord
  has_many :nominatings
  has_many :movies, through: :nominatings

end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: {maximum: 140 }

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets

   validates :username, presence: true, uniqueness: true, length: {minimum: 6}
   validates :name, presence: true

   acts_as_followable
   acts_as_follower
   acts_as_voter
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def movie_params
    params.require(:movie).permit(:title, :nomination_list)
  end

end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Month Rails Project</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>



  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Home", root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "Beers", beers_path, class:"nav-link"  %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Oscars
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a><%= link_to "Movies", movies_path, class:"dropdown-item"  %></a>
              <%= link_to "Nominations", nominations_path, class:"dropdown-item"  %>
            </div>
          </li>
          <li class="nav-item">

          </li>
          <li class="nav-item">
            <%= link_to "Tweets", tweets_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us", contact_path, class:"nav-link"  %>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", signout_path, method: :delete, class:"nav-link"  %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", signin_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class:"nav-link"  %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Flash Messages -->
  <% flash.each do |name, message| %>
  <%= content_tag(:div, message, class: "alert alert-info #{name}")%>
  <% end %>

  <main class="container">

    <%= yield %>

  </main>
  <!-- Footer -->
  <!-- <div class="container"> -->
  <footer class="small text-muted container">
      <hr>
      <center>
        <p>© 2016 One Month</p>
      </center>
  </footer>
  <!-- </div> -->

  <script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron bg-dark">
  <div class="container">
  <h1>About us</h1>
  <p>We're working on our One Month Rails Rails project.</p>
</div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron bg-dark">
  <h1>Contact Us</h1>
  <p>Please <%= mail_to "jgarvey@gmail.com" do %>
  <strong>email me</strong>
  <% end %>with any questions.</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<div class="jumbotron jumbotron-home">
  <div class="container">
    <h1>Welcome Back!</h1>
  </div>
</div>
<% else %>
<div class="jumbotron jumbotron-home">
  <div class="container">
    <h1>Welcome</h1>
    <p>This is a website.</p>
  </div>
</div>
<div class="container">
  <div class="card-deck">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
  </div>
</div>
<% end %>